root: true
env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"

rules:
  comma-dangle: ["error", "always-multiline"]
  eol-last: ["error", "always"]
  indent: ["error", 4]
  max-len: ["error", { code: 80 }]
  no-multiple-empty-lines: ["error", { "max": 1, "maxEOF": 0 }]
  object-curly-newline: ["error", "always"]
  object-curly-spacing: ["error", "always"]
  quotes: ["error", "double"]
  semi: ["error", "always"]
